export enum Actions {
  'CREATE_PROJECT' = 'CREATE_PROJECT',
  'READ_ALL_PROJECTS' = 'READ_ALL_PROJECTS',
  'UPDATE_PROJECT' = 'UPDATE_PROJECT',
  'DELETE_PROJECT' = 'DELETE_PROJECT',
  'CREATE_TASK' = 'CREATE_TASK',
  'READ_ALL_TASKS' = 'READ_ALL_TASKS',
  'UPDATE_TASK' = 'UPDATE_TASK',
  'DELETE_TASK' = 'DELETE_TASK'
}