export enum Mutation {
  'ADD_PROJECT'= 'ADD_PROJECT',
  'ADD_TASK' = 'ADD_TASK',
  'DELETE_PROJECT' = 'DELETE_PROJECT',
  'EDIT_PROJECT' = 'EDIT_PROJECT',
  'STORE_PROJECTS' = 'STORE_PROJECTS',
  'DELETE_TASK' = 'DELETE_TASK',
  'EDIT_TASK' = 'EDIT_TASK',
  'STORE_TASKS' = 'STORE_TASKS',
  'NOTIFY' = 'NOTIFY'
}